### ISSUE TITLE
Create Google drive account

### ISSUE THREAD

**Issue by clgrof** [h4sci/shiny-survey#4]
Create Google drive account for saving / loading shinyapp data.

**Comment by clgrof** [comment]
Google drive account created.

**Comment by mbannert** [comment]
@clgrof I know there are a couple of shiny tutorials that use google drive when saving data. Just meant to remind you, that this is fine for smaller projects (including this one) and projects that work on a fixed dataset. In a survey you're looking for a _transactional_ storage. Because surveys offen have a bit of traffic shortly after the invitation (all at once) , after reminders, and shortly before the deadline. That way it's somewhat likely to person fill in the survey at the same time which might cause problems. A database handles this easier. A simple solution would would sqlite which handles the db operation in a single file. Because you'd use SQL syntax then from the start it is also easy to upgrade later on.

**Comment by clgrof** [comment]
@mbannert thank you for the advice. I will discuss it with the group. I think for now we will proceed with google drive and maybe switch to the database solution later on.
